fix: Define _XOPEN_SOURCE for iOS ucontext.h compilation
iOS SDK's ucontext.h requires _XOPEN_SOURCE to be defined before
including the header, otherwise it throws a preprocessor error:

  error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined

This adds -D_XOPEN_SOURCE=1 to CFLAGS and CXXFLAGS to make the
deprecated ucontext functions (getcontext, makecontext, swapcontext)
visible during compilation of zend_fibers.c.

Note: While these functions are deprecated and stubbed on iOS, we need
them to be declared for compilation. Runtime behavior will be tested.